controlled_joint_names:  
  - "joint_1"
  - "joint_2"
  - "joint_3"
  - "joint_4"
  - "joint_5"
  - "joint_6"

starting_hi:
- "motor_planner_hi"
- "motor_controller_hi"

starting_controllers:
- "motor_fir_planner"
- "motor_cascade_control"

load_ndlcom: true
configuration_time: 5
enable_motor: true
stop_immediately: false

after_configuration_unload:
- "motor_planner_hi"

after_configuration_hi:
- "planner_hi"
- "high_controller_hi"
- "low_controller_hi"
- "model_feedforward_hi"

after_configuration_controllers:
- "fir_planner"
- "cascade_control"
- "deflection_control"
- "model_feedforward_control"

