gain_scheduling:
  hardware_interface_ns: "link_controller_hi"
  controllers_prefix: "driven_mass_controller"
  overlapping: 0.200000
  joint_1: [4.000000, 8.000000, 12.000000, 16.000000, 20.000000 ]
  joint_2: [4.000000, 8.000000, 12.000000, 16.000000, 20.000000 ]
  joint_3: [4.000000, 6.000000 ]
  joint_4: [1.000000 ]
  joint_5: [1.000000 ]
  joint_6: [1.000000 ]

link_controller_hi:

  driven_mass_controller_0_0_0_0_0_0:
    type: "itia/control/DrivenMassController"
    setpoint_topic_name: "/link/joint_target"
    feedback_topic_name: "/elastic/joint_states"
    feedforward_topic_name: "/driven_mass/joint_feedforward"

  driven_mass_controller_1_0_0_0_0_0:
    type: "itia/control/DrivenMassController"
    setpoint_topic_name: "/link/joint_target"
    feedback_topic_name: "/elastic/joint_states"
    feedforward_topic_name: "/driven_mass/joint_feedforward"

  driven_mass_controller_2_0_0_0_0_0:
    type: "itia/control/DrivenMassController"
    setpoint_topic_name: "/link/joint_target"
    feedback_topic_name: "/elastic/joint_states"
    feedforward_topic_name: "/driven_mass/joint_feedforward"

  driven_mass_controller_3_0_0_0_0_0:
    type: "itia/control/DrivenMassController"
    setpoint_topic_name: "/link/joint_target"
    feedback_topic_name: "/elastic/joint_states"
    feedforward_topic_name: "/driven_mass/joint_feedforward"

  driven_mass_controller_4_0_0_0_0_0:
    type: "itia/control/DrivenMassController"
    setpoint_topic_name: "/link/joint_target"
    feedback_topic_name: "/elastic/joint_states"
    feedforward_topic_name: "/driven_mass/joint_feedforward"

  driven_mass_controller_0_1_0_0_0_0:
    type: "itia/control/DrivenMassController"
    setpoint_topic_name: "/link/joint_target"
    feedback_topic_name: "/elastic/joint_states"
    feedforward_topic_name: "/driven_mass/joint_feedforward"

  driven_mass_controller_1_1_0_0_0_0:
    type: "itia/control/DrivenMassController"
    setpoint_topic_name: "/link/joint_target"
    feedback_topic_name: "/elastic/joint_states"
    feedforward_topic_name: "/driven_mass/joint_feedforward"

  driven_mass_controller_2_1_0_0_0_0:
    type: "itia/control/DrivenMassController"
    setpoint_topic_name: "/link/joint_target"
    feedback_topic_name: "/elastic/joint_states"
    feedforward_topic_name: "/driven_mass/joint_feedforward"

  driven_mass_controller_3_1_0_0_0_0:
    type: "itia/control/DrivenMassController"
    setpoint_topic_name: "/link/joint_target"
    feedback_topic_name: "/elastic/joint_states"
    feedforward_topic_name: "/driven_mass/joint_feedforward"

  driven_mass_controller_4_1_0_0_0_0:
    type: "itia/control/DrivenMassController"
    setpoint_topic_name: "/link/joint_target"
    feedback_topic_name: "/elastic/joint_states"
    feedforward_topic_name: "/driven_mass/joint_feedforward"

  driven_mass_controller_0_2_0_0_0_0:
    type: "itia/control/DrivenMassController"
    setpoint_topic_name: "/link/joint_target"
    feedback_topic_name: "/elastic/joint_states"
    feedforward_topic_name: "/driven_mass/joint_feedforward"

  driven_mass_controller_1_2_0_0_0_0:
    type: "itia/control/DrivenMassController"
    setpoint_topic_name: "/link/joint_target"
    feedback_topic_name: "/elastic/joint_states"
    feedforward_topic_name: "/driven_mass/joint_feedforward"

  driven_mass_controller_2_2_0_0_0_0:
    type: "itia/control/DrivenMassController"
    setpoint_topic_name: "/link/joint_target"
    feedback_topic_name: "/elastic/joint_states"
    feedforward_topic_name: "/driven_mass/joint_feedforward"

  driven_mass_controller_3_2_0_0_0_0:
    type: "itia/control/DrivenMassController"
    setpoint_topic_name: "/link/joint_target"
    feedback_topic_name: "/elastic/joint_states"
    feedforward_topic_name: "/driven_mass/joint_feedforward"

  driven_mass_controller_4_2_0_0_0_0:
    type: "itia/control/DrivenMassController"
    setpoint_topic_name: "/link/joint_target"
    feedback_topic_name: "/elastic/joint_states"
    feedforward_topic_name: "/driven_mass/joint_feedforward"

  driven_mass_controller_0_3_0_0_0_0:
    type: "itia/control/DrivenMassController"
    setpoint_topic_name: "/link/joint_target"
    feedback_topic_name: "/elastic/joint_states"
    feedforward_topic_name: "/driven_mass/joint_feedforward"

  driven_mass_controller_1_3_0_0_0_0:
    type: "itia/control/DrivenMassController"
    setpoint_topic_name: "/link/joint_target"
    feedback_topic_name: "/elastic/joint_states"
    feedforward_topic_name: "/driven_mass/joint_feedforward"

  driven_mass_controller_2_3_0_0_0_0:
    type: "itia/control/DrivenMassController"
    setpoint_topic_name: "/link/joint_target"
    feedback_topic_name: "/elastic/joint_states"
    feedforward_topic_name: "/driven_mass/joint_feedforward"

  driven_mass_controller_3_3_0_0_0_0:
    type: "itia/control/DrivenMassController"
    setpoint_topic_name: "/link/joint_target"
    feedback_topic_name: "/elastic/joint_states"
    feedforward_topic_name: "/driven_mass/joint_feedforward"

  driven_mass_controller_4_3_0_0_0_0:
    type: "itia/control/DrivenMassController"
    setpoint_topic_name: "/link/joint_target"
    feedback_topic_name: "/elastic/joint_states"
    feedforward_topic_name: "/driven_mass/joint_feedforward"

  driven_mass_controller_0_4_0_0_0_0:
    type: "itia/control/DrivenMassController"
    setpoint_topic_name: "/link/joint_target"
    feedback_topic_name: "/elastic/joint_states"
    feedforward_topic_name: "/driven_mass/joint_feedforward"

  driven_mass_controller_1_4_0_0_0_0:
    type: "itia/control/DrivenMassController"
    setpoint_topic_name: "/link/joint_target"
    feedback_topic_name: "/elastic/joint_states"
    feedforward_topic_name: "/driven_mass/joint_feedforward"

  driven_mass_controller_2_4_0_0_0_0:
    type: "itia/control/DrivenMassController"
    setpoint_topic_name: "/link/joint_target"
    feedback_topic_name: "/elastic/joint_states"
    feedforward_topic_name: "/driven_mass/joint_feedforward"

  driven_mass_controller_3_4_0_0_0_0:
    type: "itia/control/DrivenMassController"
    setpoint_topic_name: "/link/joint_target"
    feedback_topic_name: "/elastic/joint_states"
    feedforward_topic_name: "/driven_mass/joint_feedforward"

  driven_mass_controller_4_4_0_0_0_0:
    type: "itia/control/DrivenMassController"
    setpoint_topic_name: "/link/joint_target"
    feedback_topic_name: "/elastic/joint_states"
    feedforward_topic_name: "/driven_mass/joint_feedforward"

  driven_mass_controller_0_0_1_0_0_0:
    type: "itia/control/DrivenMassController"
    setpoint_topic_name: "/link/joint_target"
    feedback_topic_name: "/elastic/joint_states"
    feedforward_topic_name: "/driven_mass/joint_feedforward"

  driven_mass_controller_1_0_1_0_0_0:
    type: "itia/control/DrivenMassController"
    setpoint_topic_name: "/link/joint_target"
    feedback_topic_name: "/elastic/joint_states"
    feedforward_topic_name: "/driven_mass/joint_feedforward"

  driven_mass_controller_2_0_1_0_0_0:
    type: "itia/control/DrivenMassController"
    setpoint_topic_name: "/link/joint_target"
    feedback_topic_name: "/elastic/joint_states"
    feedforward_topic_name: "/driven_mass/joint_feedforward"

  driven_mass_controller_3_0_1_0_0_0:
    type: "itia/control/DrivenMassController"
    setpoint_topic_name: "/link/joint_target"
    feedback_topic_name: "/elastic/joint_states"
    feedforward_topic_name: "/driven_mass/joint_feedforward"

  driven_mass_controller_4_0_1_0_0_0:
    type: "itia/control/DrivenMassController"
    setpoint_topic_name: "/link/joint_target"
    feedback_topic_name: "/elastic/joint_states"
    feedforward_topic_name: "/driven_mass/joint_feedforward"

  driven_mass_controller_0_1_1_0_0_0:
    type: "itia/control/DrivenMassController"
    setpoint_topic_name: "/link/joint_target"
    feedback_topic_name: "/elastic/joint_states"
    feedforward_topic_name: "/driven_mass/joint_feedforward"

  driven_mass_controller_1_1_1_0_0_0:
    type: "itia/control/DrivenMassController"
    setpoint_topic_name: "/link/joint_target"
    feedback_topic_name: "/elastic/joint_states"
    feedforward_topic_name: "/driven_mass/joint_feedforward"

  driven_mass_controller_2_1_1_0_0_0:
    type: "itia/control/DrivenMassController"
    setpoint_topic_name: "/link/joint_target"
    feedback_topic_name: "/elastic/joint_states"
    feedforward_topic_name: "/driven_mass/joint_feedforward"

  driven_mass_controller_3_1_1_0_0_0:
    type: "itia/control/DrivenMassController"
    setpoint_topic_name: "/link/joint_target"
    feedback_topic_name: "/elastic/joint_states"
    feedforward_topic_name: "/driven_mass/joint_feedforward"

  driven_mass_controller_4_1_1_0_0_0:
    type: "itia/control/DrivenMassController"
    setpoint_topic_name: "/link/joint_target"
    feedback_topic_name: "/elastic/joint_states"
    feedforward_topic_name: "/driven_mass/joint_feedforward"

  driven_mass_controller_0_2_1_0_0_0:
    type: "itia/control/DrivenMassController"
    setpoint_topic_name: "/link/joint_target"
    feedback_topic_name: "/elastic/joint_states"
    feedforward_topic_name: "/driven_mass/joint_feedforward"

  driven_mass_controller_1_2_1_0_0_0:
    type: "itia/control/DrivenMassController"
    setpoint_topic_name: "/link/joint_target"
    feedback_topic_name: "/elastic/joint_states"
    feedforward_topic_name: "/driven_mass/joint_feedforward"

  driven_mass_controller_2_2_1_0_0_0:
    type: "itia/control/DrivenMassController"
    setpoint_topic_name: "/link/joint_target"
    feedback_topic_name: "/elastic/joint_states"
    feedforward_topic_name: "/driven_mass/joint_feedforward"

  driven_mass_controller_3_2_1_0_0_0:
    type: "itia/control/DrivenMassController"
    setpoint_topic_name: "/link/joint_target"
    feedback_topic_name: "/elastic/joint_states"
    feedforward_topic_name: "/driven_mass/joint_feedforward"

  driven_mass_controller_4_2_1_0_0_0:
    type: "itia/control/DrivenMassController"
    setpoint_topic_name: "/link/joint_target"
    feedback_topic_name: "/elastic/joint_states"
    feedforward_topic_name: "/driven_mass/joint_feedforward"

  driven_mass_controller_0_3_1_0_0_0:
    type: "itia/control/DrivenMassController"
    setpoint_topic_name: "/link/joint_target"
    feedback_topic_name: "/elastic/joint_states"
    feedforward_topic_name: "/driven_mass/joint_feedforward"

  driven_mass_controller_1_3_1_0_0_0:
    type: "itia/control/DrivenMassController"
    setpoint_topic_name: "/link/joint_target"
    feedback_topic_name: "/elastic/joint_states"
    feedforward_topic_name: "/driven_mass/joint_feedforward"

  driven_mass_controller_2_3_1_0_0_0:
    type: "itia/control/DrivenMassController"
    setpoint_topic_name: "/link/joint_target"
    feedback_topic_name: "/elastic/joint_states"
    feedforward_topic_name: "/driven_mass/joint_feedforward"

  driven_mass_controller_3_3_1_0_0_0:
    type: "itia/control/DrivenMassController"
    setpoint_topic_name: "/link/joint_target"
    feedback_topic_name: "/elastic/joint_states"
    feedforward_topic_name: "/driven_mass/joint_feedforward"

  driven_mass_controller_4_3_1_0_0_0:
    type: "itia/control/DrivenMassController"
    setpoint_topic_name: "/link/joint_target"
    feedback_topic_name: "/elastic/joint_states"
    feedforward_topic_name: "/driven_mass/joint_feedforward"

  driven_mass_controller_0_4_1_0_0_0:
    type: "itia/control/DrivenMassController"
    setpoint_topic_name: "/link/joint_target"
    feedback_topic_name: "/elastic/joint_states"
    feedforward_topic_name: "/driven_mass/joint_feedforward"

  driven_mass_controller_1_4_1_0_0_0:
    type: "itia/control/DrivenMassController"
    setpoint_topic_name: "/link/joint_target"
    feedback_topic_name: "/elastic/joint_states"
    feedforward_topic_name: "/driven_mass/joint_feedforward"

  driven_mass_controller_2_4_1_0_0_0:
    type: "itia/control/DrivenMassController"
    setpoint_topic_name: "/link/joint_target"
    feedback_topic_name: "/elastic/joint_states"
    feedforward_topic_name: "/driven_mass/joint_feedforward"

  driven_mass_controller_3_4_1_0_0_0:
    type: "itia/control/DrivenMassController"
    setpoint_topic_name: "/link/joint_target"
    feedback_topic_name: "/elastic/joint_states"
    feedforward_topic_name: "/driven_mass/joint_feedforward"

  driven_mass_controller_4_4_1_0_0_0:
    type: "itia/control/DrivenMassController"
    setpoint_topic_name: "/link/joint_target"
    feedback_topic_name: "/elastic/joint_states"
    feedforward_topic_name: "/driven_mass/joint_feedforward"

