link_controller_hi:
  driven_mass_controller_0_0_0_0_0_0:
    joint_6:
      position_minimum_error: 0.002000
      controller:
        A:
        - [0.00000000e+00 ]
        B:
        - [0.00000000e+00, 0.00000000e+00 ]
        Baw:
        - [0.00000000e+00 ]
        C:
        - [0.00000000e+00 ]
        D:
        - [1.00000000e-01, 0.00000000e+00 ]
        max_output:
        - [5.00000000e-02 ]
        min_output:
        - [-5.00000000e-02 ]
        initial_state:
        - [0.00000000e+00 ]
        initialization_matrix:
        - [0.00000000e+00 ]
      target_filter: 
        A:
        - [6.06530660e-01 ]
        B:
        - [3.93469340e-01 ]
        Baw:
        - [0.00000000e+00 ]
        C:
        - [1.00000000e+00 ]
        D:
        - [0.00000000e+00 ]
        max_output:
        - [1.00000000e+08 ]
        min_output:
        - [-1.00000000e+08 ]
        initial_state:
        - [0.00000000e+00 ]
        initialization_matrix:
        - [1.00000000e+00 ]
      link_pos_filter: 
        A:
        - [6.06530660e-01 ]
        B:
        - [3.93469340e-01 ]
        Baw:
        - [0.00000000e+00 ]
        C:
        - [1.00000000e+00 ]
        D:
        - [0.00000000e+00 ]
        max_output:
        - [1.00000000e+08 ]
        min_output:
        - [-1.00000000e+08 ]
        initial_state:
        - [0.00000000e+00 ]
        initialization_matrix:
        - [1.00000000e+00 ]
      link_vel_filter: 
        A:
        - [6.06530660e-01 ]
        B:
        - [3.93469340e-01 ]
        Baw:
        - [0.00000000e+00 ]
        C:
        - [1.00000000e+00 ]
        D:
        - [0.00000000e+00 ]
        max_output:
        - [1.00000000e+08 ]
        min_output:
        - [-1.00000000e+08 ]
        initial_state:
        - [0.00000000e+00 ]
        initialization_matrix:
        - [1.00000000e+00 ]
  driven_mass_controller_1_0_0_0_0_0:
    joint_6:
      position_minimum_error: 0.002000
      controller:
        A:
        - [0.00000000e+00 ]
        B:
        - [0.00000000e+00, 0.00000000e+00 ]
        Baw:
        - [0.00000000e+00 ]
        C:
        - [0.00000000e+00 ]
        D:
        - [1.00000000e-01, 0.00000000e+00 ]
        max_output:
        - [5.00000000e-02 ]
        min_output:
        - [-5.00000000e-02 ]
        initial_state:
        - [0.00000000e+00 ]
        initialization_matrix:
        - [0.00000000e+00 ]
      target_filter: 
        A:
        - [6.06530660e-01 ]
        B:
        - [3.93469340e-01 ]
        Baw:
        - [0.00000000e+00 ]
        C:
        - [1.00000000e+00 ]
        D:
        - [0.00000000e+00 ]
        max_output:
        - [1.00000000e+08 ]
        min_output:
        - [-1.00000000e+08 ]
        initial_state:
        - [0.00000000e+00 ]
        initialization_matrix:
        - [1.00000000e+00 ]
      link_pos_filter: 
        A:
        - [6.06530660e-01 ]
        B:
        - [3.93469340e-01 ]
        Baw:
        - [0.00000000e+00 ]
        C:
        - [1.00000000e+00 ]
        D:
        - [0.00000000e+00 ]
        max_output:
        - [1.00000000e+08 ]
        min_output:
        - [-1.00000000e+08 ]
        initial_state:
        - [0.00000000e+00 ]
        initialization_matrix:
        - [1.00000000e+00 ]
      link_vel_filter: 
        A:
        - [6.06530660e-01 ]
        B:
        - [3.93469340e-01 ]
        Baw:
        - [0.00000000e+00 ]
        C:
        - [1.00000000e+00 ]
        D:
        - [0.00000000e+00 ]
        max_output:
        - [1.00000000e+08 ]
        min_output:
        - [-1.00000000e+08 ]
        initial_state:
        - [0.00000000e+00 ]
        initialization_matrix:
        - [1.00000000e+00 ]
  driven_mass_controller_2_0_0_0_0_0:
    joint_6:
      position_minimum_error: 0.002000
      controller:
        A:
        - [0.00000000e+00 ]
        B:
        - [0.00000000e+00, 0.00000000e+00 ]
        Baw:
        - [0.00000000e+00 ]
        C:
        - [0.00000000e+00 ]
        D:
        - [1.00000000e-01, 0.00000000e+00 ]
        max_output:
        - [5.00000000e-02 ]
        min_output:
        - [-5.00000000e-02 ]
        initial_state:
        - [0.00000000e+00 ]
        initialization_matrix:
        - [0.00000000e+00 ]
      target_filter: 
        A:
        - [6.06530660e-01 ]
        B:
        - [3.93469340e-01 ]
        Baw:
        - [0.00000000e+00 ]
        C:
        - [1.00000000e+00 ]
        D:
        - [0.00000000e+00 ]
        max_output:
        - [1.00000000e+08 ]
        min_output:
        - [-1.00000000e+08 ]
        initial_state:
        - [0.00000000e+00 ]
        initialization_matrix:
        - [1.00000000e+00 ]
      link_pos_filter: 
        A:
        - [6.06530660e-01 ]
        B:
        - [3.93469340e-01 ]
        Baw:
        - [0.00000000e+00 ]
        C:
        - [1.00000000e+00 ]
        D:
        - [0.00000000e+00 ]
        max_output:
        - [1.00000000e+08 ]
        min_output:
        - [-1.00000000e+08 ]
        initial_state:
        - [0.00000000e+00 ]
        initialization_matrix:
        - [1.00000000e+00 ]
      link_vel_filter: 
        A:
        - [6.06530660e-01 ]
        B:
        - [3.93469340e-01 ]
        Baw:
        - [0.00000000e+00 ]
        C:
        - [1.00000000e+00 ]
        D:
        - [0.00000000e+00 ]
        max_output:
        - [1.00000000e+08 ]
        min_output:
        - [-1.00000000e+08 ]
        initial_state:
        - [0.00000000e+00 ]
        initialization_matrix:
        - [1.00000000e+00 ]
  driven_mass_controller_0_1_0_0_0_0:
    joint_6:
      position_minimum_error: 0.002000
      controller:
        A:
        - [0.00000000e+00 ]
        B:
        - [0.00000000e+00, 0.00000000e+00 ]
        Baw:
        - [0.00000000e+00 ]
        C:
        - [0.00000000e+00 ]
        D:
        - [1.00000000e-01, 0.00000000e+00 ]
        max_output:
        - [5.00000000e-02 ]
        min_output:
        - [-5.00000000e-02 ]
        initial_state:
        - [0.00000000e+00 ]
        initialization_matrix:
        - [0.00000000e+00 ]
      target_filter: 
        A:
        - [6.06530660e-01 ]
        B:
        - [3.93469340e-01 ]
        Baw:
        - [0.00000000e+00 ]
        C:
        - [1.00000000e+00 ]
        D:
        - [0.00000000e+00 ]
        max_output:
        - [1.00000000e+08 ]
        min_output:
        - [-1.00000000e+08 ]
        initial_state:
        - [0.00000000e+00 ]
        initialization_matrix:
        - [1.00000000e+00 ]
      link_pos_filter: 
        A:
        - [6.06530660e-01 ]
        B:
        - [3.93469340e-01 ]
        Baw:
        - [0.00000000e+00 ]
        C:
        - [1.00000000e+00 ]
        D:
        - [0.00000000e+00 ]
        max_output:
        - [1.00000000e+08 ]
        min_output:
        - [-1.00000000e+08 ]
        initial_state:
        - [0.00000000e+00 ]
        initialization_matrix:
        - [1.00000000e+00 ]
      link_vel_filter: 
        A:
        - [6.06530660e-01 ]
        B:
        - [3.93469340e-01 ]
        Baw:
        - [0.00000000e+00 ]
        C:
        - [1.00000000e+00 ]
        D:
        - [0.00000000e+00 ]
        max_output:
        - [1.00000000e+08 ]
        min_output:
        - [-1.00000000e+08 ]
        initial_state:
        - [0.00000000e+00 ]
        initialization_matrix:
        - [1.00000000e+00 ]
  driven_mass_controller_1_1_0_0_0_0:
    joint_6:
      position_minimum_error: 0.002000
      controller:
        A:
        - [0.00000000e+00 ]
        B:
        - [0.00000000e+00, 0.00000000e+00 ]
        Baw:
        - [0.00000000e+00 ]
        C:
        - [0.00000000e+00 ]
        D:
        - [1.00000000e-01, 0.00000000e+00 ]
        max_output:
        - [5.00000000e-02 ]
        min_output:
        - [-5.00000000e-02 ]
        initial_state:
        - [0.00000000e+00 ]
        initialization_matrix:
        - [0.00000000e+00 ]
      target_filter: 
        A:
        - [6.06530660e-01 ]
        B:
        - [3.93469340e-01 ]
        Baw:
        - [0.00000000e+00 ]
        C:
        - [1.00000000e+00 ]
        D:
        - [0.00000000e+00 ]
        max_output:
        - [1.00000000e+08 ]
        min_output:
        - [-1.00000000e+08 ]
        initial_state:
        - [0.00000000e+00 ]
        initialization_matrix:
        - [1.00000000e+00 ]
      link_pos_filter: 
        A:
        - [6.06530660e-01 ]
        B:
        - [3.93469340e-01 ]
        Baw:
        - [0.00000000e+00 ]
        C:
        - [1.00000000e+00 ]
        D:
        - [0.00000000e+00 ]
        max_output:
        - [1.00000000e+08 ]
        min_output:
        - [-1.00000000e+08 ]
        initial_state:
        - [0.00000000e+00 ]
        initialization_matrix:
        - [1.00000000e+00 ]
      link_vel_filter: 
        A:
        - [6.06530660e-01 ]
        B:
        - [3.93469340e-01 ]
        Baw:
        - [0.00000000e+00 ]
        C:
        - [1.00000000e+00 ]
        D:
        - [0.00000000e+00 ]
        max_output:
        - [1.00000000e+08 ]
        min_output:
        - [-1.00000000e+08 ]
        initial_state:
        - [0.00000000e+00 ]
        initialization_matrix:
        - [1.00000000e+00 ]
  driven_mass_controller_2_1_0_0_0_0:
    joint_6:
      position_minimum_error: 0.002000
      controller:
        A:
        - [0.00000000e+00 ]
        B:
        - [0.00000000e+00, 0.00000000e+00 ]
        Baw:
        - [0.00000000e+00 ]
        C:
        - [0.00000000e+00 ]
        D:
        - [1.00000000e-01, 0.00000000e+00 ]
        max_output:
        - [5.00000000e-02 ]
        min_output:
        - [-5.00000000e-02 ]
        initial_state:
        - [0.00000000e+00 ]
        initialization_matrix:
        - [0.00000000e+00 ]
      target_filter: 
        A:
        - [6.06530660e-01 ]
        B:
        - [3.93469340e-01 ]
        Baw:
        - [0.00000000e+00 ]
        C:
        - [1.00000000e+00 ]
        D:
        - [0.00000000e+00 ]
        max_output:
        - [1.00000000e+08 ]
        min_output:
        - [-1.00000000e+08 ]
        initial_state:
        - [0.00000000e+00 ]
        initialization_matrix:
        - [1.00000000e+00 ]
      link_pos_filter: 
        A:
        - [6.06530660e-01 ]
        B:
        - [3.93469340e-01 ]
        Baw:
        - [0.00000000e+00 ]
        C:
        - [1.00000000e+00 ]
        D:
        - [0.00000000e+00 ]
        max_output:
        - [1.00000000e+08 ]
        min_output:
        - [-1.00000000e+08 ]
        initial_state:
        - [0.00000000e+00 ]
        initialization_matrix:
        - [1.00000000e+00 ]
      link_vel_filter: 
        A:
        - [6.06530660e-01 ]
        B:
        - [3.93469340e-01 ]
        Baw:
        - [0.00000000e+00 ]
        C:
        - [1.00000000e+00 ]
        D:
        - [0.00000000e+00 ]
        max_output:
        - [1.00000000e+08 ]
        min_output:
        - [-1.00000000e+08 ]
        initial_state:
        - [0.00000000e+00 ]
        initialization_matrix:
        - [1.00000000e+00 ]
  driven_mass_controller_0_2_0_0_0_0:
    joint_6:
      position_minimum_error: 0.002000
      controller:
        A:
        - [0.00000000e+00 ]
        B:
        - [0.00000000e+00, 0.00000000e+00 ]
        Baw:
        - [0.00000000e+00 ]
        C:
        - [0.00000000e+00 ]
        D:
        - [1.00000000e-01, 0.00000000e+00 ]
        max_output:
        - [5.00000000e-02 ]
        min_output:
        - [-5.00000000e-02 ]
        initial_state:
        - [0.00000000e+00 ]
        initialization_matrix:
        - [0.00000000e+00 ]
      target_filter: 
        A:
        - [6.06530660e-01 ]
        B:
        - [3.93469340e-01 ]
        Baw:
        - [0.00000000e+00 ]
        C:
        - [1.00000000e+00 ]
        D:
        - [0.00000000e+00 ]
        max_output:
        - [1.00000000e+08 ]
        min_output:
        - [-1.00000000e+08 ]
        initial_state:
        - [0.00000000e+00 ]
        initialization_matrix:
        - [1.00000000e+00 ]
      link_pos_filter: 
        A:
        - [6.06530660e-01 ]
        B:
        - [3.93469340e-01 ]
        Baw:
        - [0.00000000e+00 ]
        C:
        - [1.00000000e+00 ]
        D:
        - [0.00000000e+00 ]
        max_output:
        - [1.00000000e+08 ]
        min_output:
        - [-1.00000000e+08 ]
        initial_state:
        - [0.00000000e+00 ]
        initialization_matrix:
        - [1.00000000e+00 ]
      link_vel_filter: 
        A:
        - [6.06530660e-01 ]
        B:
        - [3.93469340e-01 ]
        Baw:
        - [0.00000000e+00 ]
        C:
        - [1.00000000e+00 ]
        D:
        - [0.00000000e+00 ]
        max_output:
        - [1.00000000e+08 ]
        min_output:
        - [-1.00000000e+08 ]
        initial_state:
        - [0.00000000e+00 ]
        initialization_matrix:
        - [1.00000000e+00 ]
  driven_mass_controller_1_2_0_0_0_0:
    joint_6:
      position_minimum_error: 0.002000
      controller:
        A:
        - [0.00000000e+00 ]
        B:
        - [0.00000000e+00, 0.00000000e+00 ]
        Baw:
        - [0.00000000e+00 ]
        C:
        - [0.00000000e+00 ]
        D:
        - [1.00000000e-01, 0.00000000e+00 ]
        max_output:
        - [5.00000000e-02 ]
        min_output:
        - [-5.00000000e-02 ]
        initial_state:
        - [0.00000000e+00 ]
        initialization_matrix:
        - [0.00000000e+00 ]
      target_filter: 
        A:
        - [6.06530660e-01 ]
        B:
        - [3.93469340e-01 ]
        Baw:
        - [0.00000000e+00 ]
        C:
        - [1.00000000e+00 ]
        D:
        - [0.00000000e+00 ]
        max_output:
        - [1.00000000e+08 ]
        min_output:
        - [-1.00000000e+08 ]
        initial_state:
        - [0.00000000e+00 ]
        initialization_matrix:
        - [1.00000000e+00 ]
      link_pos_filter: 
        A:
        - [6.06530660e-01 ]
        B:
        - [3.93469340e-01 ]
        Baw:
        - [0.00000000e+00 ]
        C:
        - [1.00000000e+00 ]
        D:
        - [0.00000000e+00 ]
        max_output:
        - [1.00000000e+08 ]
        min_output:
        - [-1.00000000e+08 ]
        initial_state:
        - [0.00000000e+00 ]
        initialization_matrix:
        - [1.00000000e+00 ]
      link_vel_filter: 
        A:
        - [6.06530660e-01 ]
        B:
        - [3.93469340e-01 ]
        Baw:
        - [0.00000000e+00 ]
        C:
        - [1.00000000e+00 ]
        D:
        - [0.00000000e+00 ]
        max_output:
        - [1.00000000e+08 ]
        min_output:
        - [-1.00000000e+08 ]
        initial_state:
        - [0.00000000e+00 ]
        initialization_matrix:
        - [1.00000000e+00 ]
  driven_mass_controller_2_2_0_0_0_0:
    joint_6:
      position_minimum_error: 0.002000
      controller:
        A:
        - [0.00000000e+00 ]
        B:
        - [0.00000000e+00, 0.00000000e+00 ]
        Baw:
        - [0.00000000e+00 ]
        C:
        - [0.00000000e+00 ]
        D:
        - [1.00000000e-01, 0.00000000e+00 ]
        max_output:
        - [5.00000000e-02 ]
        min_output:
        - [-5.00000000e-02 ]
        initial_state:
        - [0.00000000e+00 ]
        initialization_matrix:
        - [0.00000000e+00 ]
      target_filter: 
        A:
        - [6.06530660e-01 ]
        B:
        - [3.93469340e-01 ]
        Baw:
        - [0.00000000e+00 ]
        C:
        - [1.00000000e+00 ]
        D:
        - [0.00000000e+00 ]
        max_output:
        - [1.00000000e+08 ]
        min_output:
        - [-1.00000000e+08 ]
        initial_state:
        - [0.00000000e+00 ]
        initialization_matrix:
        - [1.00000000e+00 ]
      link_pos_filter: 
        A:
        - [6.06530660e-01 ]
        B:
        - [3.93469340e-01 ]
        Baw:
        - [0.00000000e+00 ]
        C:
        - [1.00000000e+00 ]
        D:
        - [0.00000000e+00 ]
        max_output:
        - [1.00000000e+08 ]
        min_output:
        - [-1.00000000e+08 ]
        initial_state:
        - [0.00000000e+00 ]
        initialization_matrix:
        - [1.00000000e+00 ]
      link_vel_filter: 
        A:
        - [6.06530660e-01 ]
        B:
        - [3.93469340e-01 ]
        Baw:
        - [0.00000000e+00 ]
        C:
        - [1.00000000e+00 ]
        D:
        - [0.00000000e+00 ]
        max_output:
        - [1.00000000e+08 ]
        min_output:
        - [-1.00000000e+08 ]
        initial_state:
        - [0.00000000e+00 ]
        initialization_matrix:
        - [1.00000000e+00 ]
