gain_scheduling:
  hardware_interface_ns: "link_controller_hi"
  controllers_prefix: "driven_mass_controller"
  overlapping: 0.200000
  joint_1: [0.400000, 1.000000, 2.000000 ]
  joint_2: [1.000000, 2.000000, 4.000000 ]
  joint_3: [1.000000 ]
  joint_4: [0.500000 ]
  joint_5: [0.200000 ]
  joint_6: [0.100000 ]

link_controller_hi:

  driven_mass_controller_0_0_0_0_0_0:
    type: "itia/control/DrivenMassController"
    setpoint_topic_name: "/link/joint_target"
    feedback_topic_name: "/elastic/joint_states"
    feedforward_topic_name: "/driven_mass/joint_feedforward"

  driven_mass_controller_1_0_0_0_0_0:
    type: "itia/control/DrivenMassController"
    setpoint_topic_name: "/link/joint_target"
    feedback_topic_name: "/elastic/joint_states"
    feedforward_topic_name: "/driven_mass/joint_feedforward"

  driven_mass_controller_2_0_0_0_0_0:
    type: "itia/control/DrivenMassController"
    setpoint_topic_name: "/link/joint_target"
    feedback_topic_name: "/elastic/joint_states"
    feedforward_topic_name: "/driven_mass/joint_feedforward"

  driven_mass_controller_0_1_0_0_0_0:
    type: "itia/control/DrivenMassController"
    setpoint_topic_name: "/link/joint_target"
    feedback_topic_name: "/elastic/joint_states"
    feedforward_topic_name: "/driven_mass/joint_feedforward"

  driven_mass_controller_1_1_0_0_0_0:
    type: "itia/control/DrivenMassController"
    setpoint_topic_name: "/link/joint_target"
    feedback_topic_name: "/elastic/joint_states"
    feedforward_topic_name: "/driven_mass/joint_feedforward"

  driven_mass_controller_2_1_0_0_0_0:
    type: "itia/control/DrivenMassController"
    setpoint_topic_name: "/link/joint_target"
    feedback_topic_name: "/elastic/joint_states"
    feedforward_topic_name: "/driven_mass/joint_feedforward"

  driven_mass_controller_0_2_0_0_0_0:
    type: "itia/control/DrivenMassController"
    setpoint_topic_name: "/link/joint_target"
    feedback_topic_name: "/elastic/joint_states"
    feedforward_topic_name: "/driven_mass/joint_feedforward"

  driven_mass_controller_1_2_0_0_0_0:
    type: "itia/control/DrivenMassController"
    setpoint_topic_name: "/link/joint_target"
    feedback_topic_name: "/elastic/joint_states"
    feedforward_topic_name: "/driven_mass/joint_feedforward"

  driven_mass_controller_2_2_0_0_0_0:
    type: "itia/control/DrivenMassController"
    setpoint_topic_name: "/link/joint_target"
    feedback_topic_name: "/elastic/joint_states"
    feedforward_topic_name: "/driven_mass/joint_feedforward"

