controlled_joint_names:  
  - "joint_1"
  - "joint_2"
  - "joint_3"
  - "joint_4"
  - "joint_5"
  - "joint_6"

starting_hi:
- "planner_hi"
- "motor_controller_hi"

starting_controllers:
- "fir_planner"
- "motor_cascade_control"

load_ndlcom: false
configuration_time: 5
enable_motor: true
stop_immediately: false
starting_controller: "link_controller"