env_param:
  joint_torque_limit: [50, 50, 50, 20, 20, 20]
  tcp_force_limit:
    x: 50 # 20  # X-Force N
    y: 50 # 20  # Y-Force N
    z: 50 # 20  # Z-Force N
    a: 50   # X-Torque Nm
    b: 50   # Y-Torque Nm
    c: 50   # Z-Torque Nm
