ndlcom:
  joint_2:
    device_class: "SerialElasticJoint"
    ignored_errors:
    - "CTRL_LIMIT"
    - "SENSOR_HALL"
    - "SENSOR_ICHAUS"
    - "POSITIONDIFFERENCE"
    - "FRICTION_IDENT"
    - "SENSOR_OPTO"
    controller_class: "SerialElasticJointController"
    elasticity: 580.8
    control_mode: 3
    # 1 -> coppia
    # 3 -> cascata velocita/coppia

    registers:
      CUR_P: 4.0
      CUR_I: 100.0
      CUR_D: 0.00
      VEL_P: 2.0
      VEL_I: 16.0
      VEL_D: 0.00
      POS_P: 16.0
      POS_I: 0.0
      POS_D: 0.0
      CUR_MAX: 9.0
      CUR_MAX_HARD_LIMIT: 10.0
      CUR_DEAD_ZONE: 0.0
      VEL_DEAD_ZONE: 0.00 
      POS_DEAD_ZONE: 0.001
