move_group:
  controller_list:
    - name: ""
      action_ns: "/planner_hi/fir_planner/follow_joint_trajectory"
      type: FollowJointTrajectory
      joints:
        - joint_1
        - joint_2
        - joint_3
        - joint_4
        - joint_5
        - joint_6

      

controllers:
  motor:
    motor_planner_hi: "motor_fir_planner"
    fake_hi: "fake_controller"
    velocity_sensor_hi: "velocity_sensor"
    target_velocity_sensor_hi: "target_velocity_sensor"
  link_controller:
    planner_hi: "fir_planner"
    fake_hi: "fake_controller"
    velocity_sensor_hi: "velocity_sensor"
    target_velocity_sensor_hi: "target_velocity_sensor"
  stopped:
    fake_hi: "fake_controller"
    velocity_sensor_hi: "velocity_sensor"
    target_velocity_sensor_hi: "target_velocity_sensor"
  joint_teleop:
    planner_hi: "joint_teleop_planner"
    fake_hi: "fake_controller"
    velocity_sensor_hi: "velocity_sensor"
    target_velocity_sensor_hi: "target_velocity_sensor"
  cart_teleop:
    planner_hi: "cart_teleop_planner"
    fake_hi: "fake_controller"
  manual_guidance:
    planner_hi: "fir_planner"
    fake_hi: "fake_controller"
    velocity_sensor_hi: "velocity_sensor"
    target_velocity_sensor_hi: "target_velocity_sensor"
  impedance_soft:
    planner_hi_imp: "fir_planner_imp"
    velocity_sensor_hi: "velocity_sensor"
    impedance_hi: "impedance_soft"
    fake_hi: "fake_controller"

    

    
impedance_hi:
  nodelet_hardware_interface:
    sampling_period: 1.0e-3
    topic_name: "/link/joint_target"

  impedance_soft:  
    type: "itia/control/CartImpedanceControl"
    setpoint_topic_name: "/link/joint_target_imp"
    external_wrench_topic_name: "/external_wrench"
    adaptivity_topic_name: "/stiffness_recommendation"
    inertia: [30, 30, 30, 3, 3, 3]
    damping: [350, 350, 350, 35, 35, 35]
    stiffness_max: [1000, 1000, 1000, 300, 300, 300]
    stiffness_min: [100, 100, 100, 10, 10, 10]
    wrench_deadband: [20, 20, 20, 2, 2, 2]
    joint_acc_deadband: [0.05, 0.05, 0.05, 0.05, 0.05, 0.05]  
    base_frame: "base"
    tool_frame: "flange"
    base_is_reference: true   # ONLT BASE IMPLEMENTATION FOR NOW

motor_planner_hi:
  nodelet_hardware_interface:
    sampling_period: 1.0e-3
    topic_name: "/link/joint_target"

  motor_fir_planner:
    type: "itia/motion/FirController"
    feedback_topic_name: "/link/joint_states"

    fir_params:
      sample_period: 0.001  
      cruise_jnt_vel: [0.5, 0.5, 0.5, 0.5, 0.5, 0.5]
      acc_vel_ratio: 0.25   # acc/vel
      default_path_accuracy: 0.1
      default_goal_accuracy: 0
      np: 2
      
velocity_sensor_hi:
  nodelet_hardware_interface:
    sampling_period: 1.0e-3
    topic_name: "/none"

  velocity_sensor:
    type: "itia/control/VelocitySensor"
    setpoint_topic_name: "/link/joint_states"
    twist_topic_name: "/link/twist"
    base_frame: "base"
    tool_frame: "flange"
    base_is_reference: true   # true base_frame, false tool frame
    velocity_filtering_coeff: 0.95 # exp(-sampling_period/time_constant)
    
target_velocity_sensor_hi:
  nodelet_hardware_interface:
    sampling_period: 1.0e-3
    topic_name: "/none"

  target_velocity_sensor:
    type: "itia/control/VelocitySensor"
    setpoint_topic_name: "/link/joint_target"
    twist_topic_name: "/link/twist_target"
    base_frame: "base"
    tool_frame: "flange"
    base_is_reference: true   # true base_frame, false tool frame
    velocity_filtering_coeff: 0.95 # exp(-sampling_period/time_constant)
    
fake_hi:
  nodelet_hardware_interface:
    sampling_period: 1.0e-3
    topic_name: "/link/joint_states"

  fake_controller:
    type: "itia/FakeControllerSystem"
    setpoint_topic_name: "/link/joint_target"
    initial_position: [0.0, 0.0, 1.507, 0.0, 1.507, 0.0]

    
planner_hi_imp:
  nodelet_hardware_interface:
    sampling_period: 1.0e-3
    topic_name: "/link/joint_target_imp"
  fir_planner_imp:
    type: "itia/motion/FirController"
    feedback_topic_name: "/link/joint_states"
    fir_params:
      sample_period: 0.001  
      cruise_jnt_vel: [0.5, 0.5, 0.5, 0.5, 0.5, 0.5]
      acc_vel_ratio: 1   # acc/vel
      default_path_accuracy: 0.1
      default_goal_accuracy: 0
      np: 2  

    
planner_hi:
  nodelet_hardware_interface:
    sampling_period: 1.0e-3
    topic_name: "/link/joint_target"

  fir_planner:
    type: "itia/motion/FirController"
    feedback_topic_name: "/link/joint_states"
    fir_params:
      sample_period: 0.001  
      cruise_jnt_vel: [0.5, 0.5, 0.5, 0.5, 0.5, 0.5]
      acc_vel_ratio: 1   # acc/vel
      default_path_accuracy: 0.1
      default_goal_accuracy: 0
      np: 2  
      stop_when_zero_override: true
      

  joint_teleop_planner:
    type: "itia/motion/JointTeleopFirController"
    feedback_topic_name: "/link/joint_states"
    setpoint_topic_name: "/gui/joint_movements"
    message_timeout: 0.010 #time interval where the last message is consired valid, then the speed is set to zero
    fir_params:
      sample_period: 0.001  
      cruise_jnt_vel: [0.25, 0.25, 0.25, 0.25, 0.25, 0.25]
      acc_vel_ratio: 4.0   # acc/vel
      default_path_accuracy: 0.01
      default_goal_accuracy: 0
      np: 2  

  cart_teleop_planner:
    type: "itia/motion/CartTeleopFirController"
    feedback_topic_name: "/link/joint_states"
    setpoint_topic_name: "/gui/cartesian_movement"
    base_frame: "ACTIVE_FRAME"
    tool_frame: "ACTIVE_TOOL"
    message_timeout: 0.010 #time interval where the last message is consired valid, then the speed is set to zero
    fir_params:
      sample_period: 0.001  
      cruise_jnt_vel: [0.25, 0.25, 0.25, 0.25, 0.25, 0.25]
      acc_vel_ratio: 4.0   # acc/vel
      default_path_accuracy: 0.01
      default_goal_accuracy: 0
      np: 2  
